In [ ]:
import numpy as np

# 1. 가상의 이미지
image = np.array([
    [0, 0, 0, 0, 0],
    [0, 1, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 0, 0, 0]
])

# 2. 필터(kernel) : 3x3, 세로 윤곽선을 찾는 필터
kernel = np.array([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
])

# 3. 출력 행렬의 크기 계산 : 출력크기 = 입력크기 - 필터크기 + 1 = 5 - 3 + 1 = 3
img_h, img_w = image.shape
kernel_h, kernel_w = kernel.shape

out_h = img_h - kernel_h + 1
out_w = img_w - kernel_w + 1

output = np.zeros((out_h, out_w))

# 4. 합성곱 연산(sliding window)
for h in range(out_h):
    for w in range(out_w):
        # 이미지에서 필터크기만큼 관심영역(ROI)를 잘라냄
        roi = image[h:h+kernel_h, w:w+kernel_w]
        # 합성곱 : elementwise로 곱한뒤 합계를 구함
        output[h, w] = np.sum(roi * kernel)

# 결과는 3*3 행렬이므로 왜곡이 발생(원본의 왼쪽 윤곽선은 두번째 컬럼인데 결과에서는 첫번째 컬럼이 윤곽선처럼 인식됨)
print('original image', image, sep='\n')
print('\n세로 윤곽선 필터 적용 결과', output, sep='\n')

original image
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]

세로 윤곽선 필터 적용 결과
[[ 2.  0. -2.]
 [ 3.  0. -3.]
 [ 2.  0. -2.]]


In [ ]:
# 패딩을 도입해서 원본과 결과물의 좌표를 일치시킴
import numpy as np

# 1. 가상의 이미지
image = np.array([
    [0, 0, 0, 0, 0],
    [0, 1, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 0, 0, 0]
])

# 2. 필터(kernel) : 3x3, 세로 윤곽선을 찾는 필터
kernel = np.array([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
])

# 제로 패딩 적용(np.pad)
padded_image = np.pad(image, pad_width=1, mode='constant', constant_values=0)

# 3. 출력 행렬의 크기 계산 : 출력크기 = 입력크기 - 필터크기 + 1 = 5 - 3 + 1 = 3
img_h, img_w = image.shape
kernel_h, kernel_w = kernel.shape
pad_h, pad_w = padded_image.shape
out_h = pad_h - kernel_h + 1
out_w = pad_w - kernel_w + 1
output = np.zeros((out_h, out_w))

# 4. 합성곱 연산(sliding window)
for h in range(out_h):
    for w in range(out_w):
        # 이미지에서 필터크기만큼 관심영역(ROI)를 잘라냄
        roi = padded_image[h:h+kernel_h, w:w+kernel_w]
        # 합성곱 : elementwise로 곱한뒤 합계를 구함
        output[h, w] = np.sum(roi * kernel)

# 패딩 적용 결과 : 원본 이미지와 같은 크기의 행렬이지만 모호한 경계...
print('original image', image, sep='\n')
print('\npadded image', padded_image, sep='\n')
print('\n패딩 적용 합성곱 결과', output, sep='\n')


original image
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]

padded image
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]

패딩 적용 합성곱 결과
[[ 1.  1.  0. -1. -1.]
 [ 2.  2.  0. -2. -2.]
 [ 3.  3.  0. -3. -3.]
 [ 2.  2.  0. -2. -2.]
 [ 1.  1.  0. -1. -1.]]


In [ ]:
# ReLU 함수 도입
# 패딩을 도입해서 원본과 결과물의 좌표를 일치시킴
import numpy as np

def fn_relu(x):
    return np.maximum(0, x)

# 1. 가상의 이미지
image = np.array([
    [0, 0, 0, 0, 0],
    [0, 1, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 0, 0, 0]
])

# 2. 필터(kernel) : 3x3, 세로 윤곽선을 찾는 필터
kernel = np.array([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
])

# 제로 패딩 적용(np.pad)
padded_image = np.pad(image, pad_width=1, mode='constant', constant_values=0)

# 3. 출력 행렬의 크기 계산 : 출력크기 = 입력크기 - 필터크기 + 1 = 5 - 3 + 1 = 3
img_h, img_w = image.shape
kernel_h, kernel_w = kernel.shape
pad_h, pad_w = padded_image.shape
out_h = pad_h - kernel_h + 1
out_w = pad_w - kernel_w + 1
output = np.zeros((out_h, out_w))

# 4. 합성곱 연산(sliding window)
for h in range(out_h):
    for w in range(out_w):
        # 이미지에서 필터크기만큼 관심영역(ROI)를 잘라냄
        roi = padded_image[h:h+kernel_h, w:w+kernel_w]
        # 합성곱 : elementwise로 곱한뒤 합계를 구함
        output[h, w] = np.sum(roi * kernel)
# 왼쪽 경계만을 남김 - 단일 특성
output = fn_relu(output)
# 패딩 적용 결과 : 원본 이미지와 같은 크기의 행렬이지만 모호한 경계...
print('original image', image, sep='\n')
print('\npadded image', padded_image, sep='\n')
print('\n패딩 적용 합성곱 결과', output, sep='\n')


original image
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]

padded image
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]

패딩 적용 합성곱 결과
[[1. 1. 0. 0. 0.]
 [2. 2. 0. 0. 0.]
 [3. 3. 0. 0. 0.]
 [2. 2. 0. 0. 0.]
 [1. 1. 0. 0. 0.]]


In [21]:
import numpy as np

def fn_relu(x):
    return np.maximum(0, x)

# 1. 가상의 이미지 (1채널)
# 1. 8x8 가상의 이미지 (중앙에 4x4 사각형 패턴)
image = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 1, 0, 0],
    [0, 0, 1, 5, 5, 1, 0, 0],  # 일부러 강한 자극(5)을 섞었습니다.
    [0, 0, 1, 5, 5, 1, 0, 0],
    [0, 0, 1, 1, 1, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0]
])

# 제로 패딩 적용
padded_image = np.pad(image, pad_width=1, mode='constant', constant_values=0)

# 2. 다중 필터(MLP의 가중치에 해당) 구성 (Shape: 2 x 3 x 3)
kernel_left = np.array([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
])

kernel_right = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])
# 두 개의 필터를 하나의 3차원 배열로 묶습니다.
kernels = np.array([kernel_left, kernel_right])
num_filters, kernel_h, kernel_w = kernels.shape # (2, 3, 3)
# 편향
b = np.zeros((num_filters, 1, 1))

# 3. 출력 행렬의 크기 계산
pad_h, pad_w = padded_image.shape
out_h = pad_h - kernel_h + 1
out_w = pad_w - kernel_w + 1

# ★ 핵심: 출력 행렬은 (필터 개수, 높이, 너비)의 3차원 형태가 됩니다. (2, 5, 5)
output = np.zeros((num_filters, out_h, out_w))

# 4. 다중 채널 합성곱 연산
for f in range(num_filters):          # 첫 번째 루프: 각 필터를 순회
    for h in range(out_h):            # 두 번째 루프: 세로 이동
        for w in range(out_w):        # 세 번째 루프: 가로 이동
            
            # 이미지에서 3x3 ROI 추출
            roi = padded_image[h:h+kernel_h, w:w+kernel_w]
            
            # f번째 필터(kernels[f])와 요소별 곱셈 후 합산
            output[f, h, w] = np.sum(roi * kernels[f])

output += b
# 5. 활성화 함수(ReLU) 적용
output_relu = fn_relu(output)

# print('original image', image, sep='\n')
print('\npadded image', padded_image, sep='\n')
print(f"출력 데이터의 형태(Shape): {output_relu.shape}\n")
print("=== 채널 0 (왼쪽 경계 특징 맵) ===")
print(output_relu[0], "\n")
print("=== 채널 1 (오른쪽 경계 특징 맵) ===")
print(output_relu[1])


padded image
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 0 0 0]
 [0 0 0 1 5 5 1 0 0 0]
 [0 0 0 1 5 5 1 0 0 0]
 [0 0 0 1 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
출력 데이터의 형태(Shape): (2, 8, 8)

=== 채널 0 (왼쪽 경계 특징 맵) ===
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  2.  6.  4.  0.  0.  0.  0.]
 [ 0.  3. 11.  8.  0.  0.  0.  0.]
 [ 0.  3. 11.  8.  0.  0.  0.  0.]
 [ 0.  2.  6.  4.  0.  0.  0.  0.]
 [ 0.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]] 

=== 채널 1 (오른쪽 경계 특징 맵) ===
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  1.  0.]
 [ 0.  0.  0.  0.  4.  6.  2.  0.]
 [ 0.  0.  0.  0.  8. 11.  3.  0.]
 [ 0.  0.  0.  0.  8. 11.  3.  0.]
 [ 0.  0.  0.  0.  4.  6.  2.  0.]
 [ 0.  0.  0.  0.  0.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [29]:
# 맥스 풀링
pool = np.zeros((num_filters, 4, 4))
for f in range(num_filters):
    for h in range(0, out_h, 2):
        i = np.int8(h /2 )
        for w in range(0, out_w, 2):
            j = np.int8(w / 2)
            cell = output_relu[f, h:h+2, w:w+2]
            pool[f, i, j] = np.max(cell)

print(pool)


[[[ 1.  1.  0.  0.]
  [ 3. 11.  0.  0.]
  [ 3. 11.  0.  0.]
  [ 1.  1.  0.  0.]]

 [[ 0.  0.  1.  1.]
  [ 0.  0. 11.  3.]
  [ 0.  0. 11.  3.]
  [ 0.  0.  1.  1.]]]


In [31]:
# 1. 설정값 정의 (나중에 3x3 등으로 바꿀 때를 대비)
pool_size = 2
stride = 2

# 2. 출력 크기 자동 계산
# (입력 크기 - 풀링 크기) // 스트라이드 + 1
pool_h = (out_h - pool_size) // stride + 1
pool_w = (out_w - pool_size) // stride + 1

pool = np.zeros((num_filters, pool_h, pool_w))

for f in range(num_filters):
    for h in range(pool_h): # 출력 행렬의 인덱스를 기준으로 루프
        for w in range(pool_w):
            # 원본 이미지에서의 시작 좌표 계산
            h_start = h * stride
            w_start = w * stride
            
            # 영역(Window) 슬라이싱 후 최댓값 추출
            window = output_relu[f, h_start : h_start + pool_size, w_start : w_start + pool_size]
            pool[f, h, w] = np.max(window)
print(pool)

[[[ 1.  1.  0.  0.]
  [ 3. 11.  0.  0.]
  [ 3. 11.  0.  0.]
  [ 1.  1.  0.  0.]]

 [[ 0.  0.  1.  1.]
  [ 0.  0. 11.  3.]
  [ 0.  0. 11.  3.]
  [ 0.  0.  1.  1.]]]


In [32]:
# (채널, 높이, 너비) -> (채널, 높이/2, 2, 너비/2, 2) 형태로 쪼갭니다.
# 그 후 3번째, 5번째 축(각 2x2 영역의 데이터들)에서 최댓값을 뽑습니다.
# 이 코드는 out_h와 out_w가 짝수일 때만 작동하는 아주 강력한 한 줄입니다.

# 차원을 5차원으로 쪼개기
reshaped = output_relu.reshape(num_filters, pool_h, pool_size, pool_w, pool_size)

# 2번, 4번 축(2x2 윈도우 내부)에 대해 최댓값을 구함
pool_fast = reshaped.max(axis=(2, 4))
print(pool_fast)

[[[ 1.  1.  0.  0.]
  [ 3. 11.  0.  0.]
  [ 3. 11.  0.  0.]
  [ 1.  1.  0.  0.]]

 [[ 0.  0.  1.  1.]
  [ 0.  0. 11.  3.]
  [ 0.  0. 11.  3.]
  [ 0.  0.  1.  1.]]]
